export const AUDIT_ACTION_LABELS: Record<string, string> = {
  create: "Tạo mới",
  update: "Cập nhật",
  delete: "Xóa",
  import: "Import",
  export: "Export",
  preview: "Tạo preview",
  commit: "Commit phương án",
  discard: "Bỏ phương án",
  retry: "Gửi lại",
  lock: "Khóa",
  unlock: "Mở khóa",
  bulk_update: "Cập nhật hàng loạt",
  manual_assign: "Xếp thủ công",
  status_advance: "Tiến trạng thái",
  status_revert: "Lùi trạng thái",
}

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  event: "Kỳ Team Building",
  accommodation: "Lưu trú",
  registration: "Đăng ký",
  employee_import: "Danh sách CBNV",
  team: "Team",
  pickup_point: "Điểm đón",
  work_location: "Nơi làm việc",
  flight: "Chuyến bay",
  flight_import: "Import chuyến bay",
  flight_assignment: "Phân chuyến",
  vehicle: "Xe",
  vehicle_assignment: "Phân xe",
  hotel: "Khách sạn",
  room_type: "Loại phòng",
  room: "Phòng",
  room_assignment: "Phân phòng",
  allocation_run: "Lượt phân bổ",
  schedule_item: "Lịch trình",
  announcement: "Thông báo",
  notification: "Email hệ thống",
  audit_log: "Nhật ký thay đổi",
}
