"use client"
import { useState } from "react"
import { BellRingIcon, CalendarDaysIcon, PencilIcon, PlusIcon, Trash2Icon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { useContent, useCreateAnnouncement, useCreateSchedule, useDeleteAnnouncement, useDeleteSchedule, useUpdateAnnouncement, useUpdateSchedule } from "../hooks/journey.hook"
import type { Announcement, AnnouncementInput, ScheduleInput, ScheduleItem } from "../service/journey.service"

type Editor = { kind: "schedule"; item?: ScheduleItem } | { kind: "announcement"; item?: Announcement }
const localDateTime = (date: Date) => { const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16) }
const displayTime = (date: Date) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(date)

export function ContentManager({ eventId }: { eventId: string }) {
  const { data } = useContent(eventId); const [editor, setEditor] = useState<Editor | null>(null)
  const removeSchedule = useDeleteSchedule(eventId); const removeAnnouncement = useDeleteAnnouncement(eventId)
  return <Tabs defaultValue="schedule" className="space-y-4"><TabsList><TabsTrigger value="schedule"><CalendarDaysIcon />Lịch trình ({data.schedule.length})</TabsTrigger><TabsTrigger value="announcements"><BellRingIcon />Thông báo ({data.announcements.length})</TabsTrigger></TabsList>
    <TabsContent value="schedule" className="space-y-4"><div className="flex justify-end"><Button onClick={() => setEditor({ kind: "schedule" })}><PlusIcon />Thêm hoạt động</Button></div>{data.schedule.length ? data.schedule.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-4 pt-6 sm:flex-row sm:items-start"><div className="min-w-28"><Badge>Ngày {item.day}</Badge><p className="mt-2 text-sm text-muted-foreground">{displayTime(item.startAt)}<br />đến {displayTime(item.endAt)}</p></div><div className="min-w-0 flex-1"><h3 className="font-medium">{item.title}</h3>{item.location && <p className="text-sm text-muted-foreground">{item.location}</p>}{item.description && <p className="mt-2 whitespace-pre-wrap text-sm">{item.description}</p>}</div><div className="flex gap-2"><Button size="icon-sm" variant="outline" aria-label="Sửa" onClick={() => setEditor({ kind: "schedule", item })}><PencilIcon /></Button><Button size="icon-sm" variant="destructive" aria-label="Xóa" onClick={() => confirm("Xóa hoạt động này?") && removeSchedule.mutate(item.id)}><Trash2Icon /></Button></div></CardContent></Card>) : <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">Chưa có lịch trình.</CardContent></Card>}</TabsContent>
    <TabsContent value="announcements" className="space-y-4"><div className="flex justify-end"><Button onClick={() => setEditor({ kind: "announcement" })}><PlusIcon />Thêm thông báo</Button></div>{data.announcements.length ? data.announcements.map((item) => <Card key={item.id}><CardHeader className="pb-2"><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{item.title}</CardTitle><div className="mt-2 flex gap-2"><Badge variant={item.publishedAt ? "default" : "secondary"}>{item.publishedAt ? "Đã công bố" : "Bản nháp"}</Badge><Badge variant="outline">{item.audience === "organizers" ? "BTC" : item.audience === "all" ? "Tất cả" : "Người tham gia"}</Badge></div></div><div className="flex gap-2"><Button size="icon-sm" variant="outline" aria-label="Sửa" onClick={() => setEditor({ kind: "announcement", item })}><PencilIcon /></Button><Button size="icon-sm" variant="destructive" aria-label="Xóa" onClick={() => confirm("Xóa thông báo này?") && removeAnnouncement.mutate(item.id)}><Trash2Icon /></Button></div></div></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm">{item.body}</p></CardContent></Card>) : <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">Chưa có thông báo.</CardContent></Card>}</TabsContent>
    {editor?.kind === "schedule" && <ScheduleDialog eventId={eventId} item={editor.item} onClose={() => setEditor(null)} />}
    {editor?.kind === "announcement" && <AnnouncementDialog eventId={eventId} item={editor.item} onClose={() => setEditor(null)} />}
  </Tabs>
}

function ScheduleDialog({ eventId, item, onClose }: { eventId: string; item?: ScheduleItem; onClose: () => void }) {
  const [value, setValue] = useState({ day: String(item?.day ?? 1), startAt: item ? localDateTime(item.startAt) : "", endAt: item ? localDateTime(item.endAt) : "", title: item?.title ?? "", location: item?.location ?? "", description: item?.description ?? "" })
  const create = useCreateSchedule(eventId), update = useUpdateSchedule(eventId, item?.id ?? "")
  const submit = () => { const input: ScheduleInput = { day: Number(value.day), startAt: new Date(value.startAt).toISOString(), endAt: new Date(value.endAt).toISOString(), title: value.title, location: value.location || null, description: value.description || null }; (item ? update : create).mutate(input, { onSuccess: onClose }) }
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{item ? "Sửa hoạt động" : "Thêm hoạt động"}</DialogTitle><DialogDescription>Lịch trình này sẽ xuất hiện trong Journey sau khi kỳ được công bố.</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel>Ngày thứ</FieldLabel><Input type="number" min={1} value={value.day} onChange={(e) => setValue({ ...value, day: e.target.value })} /></Field><Field><FieldLabel>Tiêu đề</FieldLabel><Input value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel>Bắt đầu</FieldLabel><Input type="datetime-local" value={value.startAt} onChange={(e) => setValue({ ...value, startAt: e.target.value })} /></Field><Field><FieldLabel>Kết thúc</FieldLabel><Input type="datetime-local" value={value.endAt} onChange={(e) => setValue({ ...value, endAt: e.target.value })} /></Field></div><Field><FieldLabel>Địa điểm</FieldLabel><Input value={value.location} onChange={(e) => setValue({ ...value, location: e.target.value })} /></Field><Field><FieldLabel>Mô tả</FieldLabel><Textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} /></Field></FieldGroup><DialogFooter><Button variant="outline" onClick={onClose}>Hủy</Button><Button disabled={!value.title || !value.startAt || !value.endAt || create.isPending || update.isPending} onClick={submit}>Lưu</Button></DialogFooter></DialogContent></Dialog>
}

function AnnouncementDialog({ eventId, item, onClose }: { eventId: string; item?: Announcement; onClose: () => void }) {
  const [value, setValue] = useState<AnnouncementInput>({ title: item?.title ?? "", body: item?.body ?? "", audience: item?.audience ?? "participants", published: Boolean(item?.publishedAt) })
  const create = useCreateAnnouncement(eventId), update = useUpdateAnnouncement(eventId, item?.id ?? "")
  const submit = () => (item ? update : create).mutate(value, { onSuccess: onClose })
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{item ? "Sửa thông báo" : "Thêm thông báo"}</DialogTitle><DialogDescription>Công bố sau khi kỳ đã publish sẽ tạo email cho người tham gia.</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel>Tiêu đề</FieldLabel><Input value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} /></Field><Field><FieldLabel>Nội dung</FieldLabel><Textarea className="min-h-32" value={value.body} onChange={(e) => setValue({ ...value, body: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel>Đối tượng</FieldLabel><Select value={value.audience} onValueChange={(audience: AnnouncementInput["audience"]) => setValue({ ...value, audience })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="participants">Người tham gia</SelectItem><SelectItem value="all">Tất cả</SelectItem><SelectItem value="organizers">Chỉ BTC</SelectItem></SelectContent></Select></Field><Field><FieldLabel>Trạng thái</FieldLabel><Select value={value.published ? "published" : "draft"} onValueChange={(state) => setValue({ ...value, published: state === "published" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">Bản nháp</SelectItem><SelectItem value="published">Công bố</SelectItem></SelectContent></Select></Field></div></FieldGroup><DialogFooter><Button variant="outline" onClick={onClose}>Hủy</Button><Button disabled={!value.title || !value.body || create.isPending || update.isPending} onClick={submit}>Lưu</Button></DialogFooter></DialogContent></Dialog>
}
